package com.bensamir.starter.apidocs.properties;

import java.util.ArrayList;
import java.util.List;

public class ApiDocsProperties {
    private boolean enabled = true;
    private String title = "API Documentation";
    private String description = "API Documentation generated by Spring Boot Starter Kit";
    private String version = "1.0";
    private String termsOfServiceUrl = "";
    private final ContactInfo contact = new ContactInfo();
    private final LicenseInfo license = new LicenseInfo();
    private final List<ServerInfo> servers = new ArrayList<>();

    public ApiDocsProperties() {
        // Add default server
        servers.add(new ServerInfo("http://localhost:8080", "Local Development Server"));
    }

    // Getters and setters
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getTermsOfServiceUrl() {
        return termsOfServiceUrl;
    }

    public void setTermsOfServiceUrl(String termsOfServiceUrl) {
        this.termsOfServiceUrl = termsOfServiceUrl;
    }

    public ContactInfo getContact() {
        return contact;
    }

    public LicenseInfo getLicense() {
        return license;
    }

    public List<ServerInfo> getServers() {
        return servers;
    }

    // Nested property classes
    public static class ContactInfo {
        private String name = "";
        private String url = "";
        private String email = "";

        // Getters and setters
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
    }

    public static class LicenseInfo {
        private String name = "MIT License";
        private String url = "https://opensource.org/licenses/MIT";

        // Getters and setters
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
    }

    public static class ServerInfo {
        private String url;
        private String description;

        public ServerInfo() {
        }

        public ServerInfo(String url, String description) {
            this.url = url;
            this.description = description;
        }

        // Getters and setters
        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
    }
}